### ISSUE TITLE
Some basic examples to get going ?

### ISSUE THREAD

**Issue by joeblew99** [mjibson/go-dsp#15]

**Comment by joeblew99** [comment]
Well I am trying to adapt the concepts of DSP programming to flow based reactive systems. Yes that's alot of buzz words, but there is a crossover.

**Comment by mjibson** [comment]
I do not know what flow-based reactive systems are. go-dsp is closer to a toolkit that implements some of the lower-level DSP functions. I'm not sure what I can contribute here.

**Comment by joeblew99** [comment]
OK. Well best leave it.
